image: openjdk:11

stages:
  - build
  - test
  - coverage

build-Movies-project:
  stage: build
  script:
    - ./gradlew bootJar
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 30 days

test:
  stage: test
  script:
    ./gradlew test
  artifacts:
    paths:
      - build/test-results/test/TEST*.xml
    expire_in: 30 days


codeCoverage:
  image: adoptopenjdk:11
  needs:
    - build-rescue
    - test
  stage: coverage
  script:
    - ./gradlew jacocoTestReport
    - ./gradlew jacocoTestCoverageVerification
  allow_failure: true
  artifacts:
    when: always
    paths:
      - build/reports/jacoco/

# Set up docker file
