openapi: '3.0.2'

components:
  schemas:
    Movie:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
      required:
        - id
        - title

info:
  title: Movies
  description: This is a movie API which provides endpoint to get/post/update/delete movies.
  version: '1.0'
servers:
  - url: https://api.movies.com/v1
paths:
  /movies:
    get:
      summary: returns a list of movies
      responses:
        '200':
          description: A JSON array of movie names
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Movie'
    post:
      summary: creates a list
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Movie'
      responses:
        '201':
          description: created
        '400':
          description: error
  /movies/{movie_id}:
    get:
      summary: Returns a movie matching the movie_id
      parameters:
        - name: movie_id
          in: path
          required: true
          description: The ID of the movie to be returned
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: A movie object
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Movie'
        '400':
          description: The specified movie ID is invalid
        '404':
          description: A movie with the specified ID does not exist
        default:
          description: Unexpected error