apiVersion: apps/v1
kind: Deployment
metadata:
  name: angie-movies-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angie-movies-api
  template:
    metadata:
      labels:
        app: angie-movies-api
    spec:
      containers:
        - image: registry.gitlab.com/adavidson11/movies
          name: angie-movies-api
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: 52.26.72.203
            - name: DB_NAME
              value: movies
            - name: DB_USER
              value: movie_user
            - name: DB_PWD
              value: movie_user
      imagePullSecrets: # Be sure the token name matches what you created on K8s
        - name: angie-movies-api