apiVersion: v1
kind: Service
metadata:
  name: angie-movies-api-lb
spec:
  type: LoadBalancer
  selector:
    app: angie-movies-api-lb
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http