apiVersion: v1
kind: Service
metadata:
  name: movies-lb
spec:
  type: LoadBalancer
  selector:
    app: movies-lb
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http