apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movies-api
  template:
    metadata:
      labels:
        app: movies-api
    spec:
      containers:
        - image: registry.gitlab.com/adavidson11/movies
          name: movies-api
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "$DB_HOST"
            - name: DB_NAME
              value: "$DB_NAME"
            - name: DB_USER
              value: "$DB_USER"
            - name: DB_PWD
              value: "$DB_PWD"
      imagePullSecrets: # Be sure the token name matches what you created on K8s
        - name: movies-api